import { HardwareSpecification } from './HardwareSpecification';

// 1. ARDUINO UNO R3
export const ArduinoUnoSpecification: HardwareSpecification = {
  modelNumber: 'A000066',
  manufacturer: 'Arduino LLC',
  revision: 'Rev 3',
  datasheetUrl: 'https://docs.arduino.cc/resources/datasheets/A000066-datasheet.pdf',
  dimensions: {
    widthMm: 68.6,
    heightMm: 15.0,
    depthMm: 53.4,
    massGrams: 25.0,
    mountingHolePitchMm: '50.8 x 27.9 mm (4x M3)',
  },
  electrical: {
    operatingVoltage: '5V DC',
    minVoltage: 7.0,
    maxVoltage: 12.0,
    logicLevel: '5V TTL',
    quiescentCurrentMa: 45,
    maxCurrentDrawMa: 200,
    powerRatingWatts: 1.0,
  },
  protocols: ['UART', 'SPI', 'I2C', 'PWM', '1-Wire (Bit-bang)'],
  mechanicalMounts: ['4x M3 Mounting Holes (FR4 Plated)', 'Standard 2.54mm Breadboard Header Socket'],
  features: [
    'ATmega328P 8-bit AVR Microcontroller @ 16 MHz',
    '32 KB Flash Memory (0.5 KB used by bootloader)',
    '2 KB SRAM, 1 KB EEPROM',
    '14 Digital I/O Pins (6 PWM outputs)',
    '6 Analog Input Channels (10-bit ADC)',
    'Dedicated ATmega16U2 USB-to-Serial converter',
    '500mA PTC Resettable Polyfuse Overcurrent Protection',
  ],
  subcomponents: [
    {
      id: 'sub_uno_pcb',
      name: 'Main Motherboard PCB',
      category: 'chassis',
      partNumber: 'UNO-R3-PCB-REV3',
      manufacturer: 'Arduino LLC',
      description: '1.6mm 2-Layer FR4 PCB with Italian Teal soldermask and immersion gold plated pads.',
      status: 'nominal',
      specifications: { layers: 2, thicknessMm: 1.6, finish: 'ENIG' },
    },
    {
      id: 'sub_uno_mcu',
      name: 'Main Microcontroller (MCU)',
      category: 'ic',
      partNumber: 'ATmega328P-PU',
      manufacturer: 'Microchip Technology',
      description: '8-bit AVR RISC microcontroller with 32KB ISP flash, 28-pin narrow DIP package seated in socket.',
      status: 'nominal',
      specifications: { clockMhz: 16, flashKb: 32, sramKb: 2, package: 'DIP-28' },
    },
    {
      id: 'sub_uno_usb_ic',
      name: 'USB Interface Controller',
      category: 'ic',
      partNumber: 'ATmega16U2-MU',
      manufacturer: 'Microchip Technology',
      description: 'High-performance 8-bit AVR with full-speed USB 2.0 transceiver handling USB-UART CDC bridge.',
      status: 'nominal',
      specifications: { speed: '12 Mbps Full Speed', package: 'QFN-32' },
    },
    {
      id: 'sub_uno_xtal',
      name: 'Main System Crystal Oscillator',
      category: 'passive',
      partNumber: 'HC-49S-16.000MHz',
      manufacturer: 'TXC Corporation',
      description: '16.000 MHz parallel resonant quartz crystal resonator providing clock for ATmega328P.',
      status: 'nominal',
      specifications: { frequencyMhz: 16.0, stabilityPpm: 30 },
    },
    {
      id: 'sub_uno_reg_5v',
      name: '5V Linear Voltage Regulator',
      category: 'power',
      partNumber: 'NCP1117ST50T3G',
      manufacturer: 'onsemi',
      description: 'Positive low-dropout (LDO) 1.0A voltage regulator stepping down DC barrel jack (7-12V) to 5.0V.',
      status: 'nominal',
      specifications: { outputVoltage: 5.0, maxCurrentA: 1.0, package: 'SOT-223' },
    },
    {
      id: 'sub_uno_reg_3v3',
      name: '3.3V Low-Dropout Regulator',
      category: 'power',
      partNumber: 'LP2985-33DBVR',
      manufacturer: 'Texas Instruments',
      description: 'Ultra-low-noise 150mA LDO regulator powering 3.3V shield peripherals and sensors.',
      status: 'nominal',
      specifications: { outputVoltage: 3.3, maxCurrentMa: 150, package: 'SOT-23-5' },
    },
    {
      id: 'sub_uno_usb_port',
      name: 'USB Type-B Female Receptacle',
      category: 'connector',
      partNumber: '61729-0010BLF',
      manufacturer: 'Amphenol / FCI',
      description: 'Through-hole full-size USB Type-B female connector with tin-plated steel EMI shield shell.',
      status: 'nominal',
      specifications: { rating: '30V 1.5A', matingCycles: 1500 },
    },
    {
      id: 'sub_uno_dc_jack',
      name: '2.1mm Center-Positive DC Barrel Jack',
      category: 'connector',
      partNumber: 'PJ-002A',
      manufacturer: 'CUI Devices',
      description: 'Through-hole power connector accepting 5.5mm outer / 2.1mm inner diameter DC plugs.',
      status: 'nominal',
      specifications: { centerPinMm: 2.1, rating: '24V 2.5A' },
    },
    {
      id: 'sub_uno_polyfuse',
      name: 'Resettable Polyfuse PTC',
      category: 'passive',
      partNumber: 'MF-MSMF050-2',
      manufacturer: 'Bourns',
      description: 'Polymeric positive temperature coefficient 500mA hold / 1A trip overcurrent protector for USB.',
      status: 'nominal',
      specifications: { holdCurrentMa: 500, tripCurrentMa: 1000 },
    },
    {
      id: 'sub_uno_reset_sw',
      name: 'Tactile Reset Switch',
      category: 'control',
      partNumber: 'TL3301AF160QG',
      manufacturer: 'E-Switch',
      description: 'SPST momentary push-button pulling the ATmega328P RESET pin to GND to initiate reboot.',
      status: 'nominal',
    },
  ],
};

// 2. ESP32 NODEMCU DEVKIT V1
export const ESP32Specification: HardwareSpecification = {
  modelNumber: 'ESP32-DEVKITV1',
  manufacturer: 'Espressif Systems',
  revision: 'NodeMCU V1.0',
  datasheetUrl: 'https://www.espressif.com/sites/default/files/documentation/esp32_datasheet_en.pdf',
  dimensions: {
    widthMm: 52.0,
    heightMm: 12.0,
    depthMm: 28.5,
    massGrams: 10.5,
    mountingHolePitchMm: '4x M2 corner holes',
  },
  electrical: {
    operatingVoltage: '3.3V DC (5V USB/VIN input)',
    minVoltage: 3.0,
    maxVoltage: 3.6,
    logicLevel: '3.3V LVTTL',
    quiescentCurrentMa: 80,
    maxCurrentDrawMa: 500,
    powerRatingWatts: 1.65,
  },
  protocols: ['Wi-Fi 802.11b/g/n', 'Bluetooth 4.2 BR/EDR & BLE', 'UART', 'SPI', 'I2C', 'I2S', 'PWM', 'Capacitive Touch'],
  mechanicalMounts: ['Standard 0.9" Pitch Breadboard DIP Breakout', '4x Corner Standoffs'],
  features: [
    'Dual-Core Tensilica Xtensa 32-bit LX6 Microprocessor @ 240 MHz (up to 600 DMIPS)',
    '520 KB Internal SRAM, 448 KB ROM',
    '4 MB External SPI Flash Memory',
    'Integrated 802.11 b/g/n Wi-Fi Transceiver (up to 150 Mbps)',
    'Dual-Mode Bluetooth (Classic v4.2 and BLE Low Energy)',
    '30 General-Purpose I/O Pins with ultra-low-power co-processor',
    '12-bit SAR ADC (up to 18 channels), 2x 8-bit DACs',
  ],
  subcomponents: [
    {
      id: 'sub_esp_rf_module',
      name: 'ESP-WROOM-32 RF Module',
      category: 'radio',
      partNumber: 'ESP-WROOM-32',
      manufacturer: 'Espressif Systems',
      description: 'Integrated RF shielded surface-mount module housing ESP32-D0WDQ6 SoC and 4MB SPI Flash.',
      status: 'nominal',
      specifications: { mcu: 'Dual Tensilica LX6 @ 240MHz', flashMb: 4, wifi: '802.11 b/g/n', ble: '4.2' },
    },
    {
      id: 'sub_esp_antenna',
      name: 'Inverted-F PCB Meander Antenna',
      category: 'radio',
      partNumber: 'MIFA-2.4G',
      manufacturer: 'Espressif Systems',
      description: 'Gold-plated matched meandered inverted-F trace antenna tuned for 2.400-2.4835 GHz ISM band.',
      status: 'nominal',
      specifications: { gainDbi: 2.0, bandGhz: '2.4' },
    },
    {
      id: 'sub_esp_uart_bridge',
      name: 'USB-to-UART Bridge Controller',
      category: 'ic',
      partNumber: 'CP2102-GMR',
      manufacturer: 'Silicon Labs',
      description: 'High-efficiency USB 2.0 full-speed to UART bridge with automatic RTS/DTR reset circuit for flashing.',
      status: 'nominal',
      specifications: { baudRateMax: 921600, package: 'QFN-28' },
    },
    {
      id: 'sub_esp_ldo',
      name: '3.3V Low-Dropout Voltage Regulator',
      category: 'power',
      partNumber: 'AMS1117-3.3',
      manufacturer: 'Advanced Monolithic Systems',
      description: 'SOT-223 3-terminal LDO regulator stepping down 5V USB/VIN to 3.3V clean system power (800mA max).',
      status: 'nominal',
      specifications: { outputVoltage: 3.3, maxCurrentMa: 800 },
    },
    {
      id: 'sub_esp_usb_port',
      name: 'Micro-USB Type-B Female Jack',
      category: 'connector',
      partNumber: '10118194-0001LF',
      manufacturer: 'Amphenol ICC',
      description: 'Surface-mount with through-hole shell retention tabs Micro-USB 2.0 port for power and programming.',
      status: 'nominal',
      specifications: { rating: '5V 1.8A', cycles: 10000 },
    },
    {
      id: 'sub_esp_en_btn',
      name: 'EN (Reset) Tactile Button',
      category: 'control',
      partNumber: 'SMD-TACT-3x4',
      manufacturer: 'Panasonic',
      description: 'Active-low chip reset button pulling chip enable pin EN to GND.',
      status: 'nominal',
    },
    {
      id: 'sub_esp_boot_btn',
      name: 'BOOT (GPIO0) Tactile Button',
      category: 'control',
      partNumber: 'SMD-TACT-3x4',
      manufacturer: 'Panasonic',
      description: 'Boot mode selector button holding GPIO0 low during reset to enter UART ROM download mode.',
      status: 'nominal',
    },
    {
      id: 'sub_esp_headers',
      name: 'Dual 15-Pin 2.54mm Breakout Headers',
      category: 'connector',
      partNumber: 'HDR-M-1x15-2.54',
      manufacturer: 'Harwin',
      description: 'Gold-flashed brass male pin header strips (2x 15 pins, 0.1 inch spacing) breadboard compatible.',
      status: 'nominal',
    },
  ],
};

// 3. RASPBERRY PI 4 MODEL B
export const RaspberryPiSpecification: HardwareSpecification = {
  modelNumber: 'RPI4-MODBP-4GB',
  manufacturer: 'Raspberry Pi Foundation',
  revision: 'Model B Rev 1.4',
  datasheetUrl: 'https://datasheets.raspberrypi.com/rpi4/raspberry-pi-4-datasheet.pdf',
  dimensions: {
    widthMm: 85.6,
    heightMm: 17.0,
    depthMm: 56.5,
    massGrams: 46.0,
    mountingHolePitchMm: '58.0 x 49.0 mm (4x M2.5 holes)',
  },
  electrical: {
    operatingVoltage: '5.1V DC via USB Type-C',
    minVoltage: 4.75,
    maxVoltage: 5.25,
    logicLevel: '3.3V LVTTL (Non-5V tolerant)',
    quiescentCurrentMa: 600,
    maxCurrentDrawMa: 3000,
    powerRatingWatts: 15.3,
  },
  protocols: ['Gigabit Ethernet', 'Dual-Band 802.11ac Wi-Fi', 'Bluetooth 5.0 BLE', 'USB 3.0 / 2.0', 'Dual 4K Micro-HDMI', 'MIPI CSI-2', 'MIPI DSI', 'I2C', 'SPI', 'UART'],
  mechanicalMounts: ['4x M2.5 Plated Mounting Holes', 'DIN-Rail & Enclosure Stand-offs'],
  features: [
    'Broadcom BCM2711, Quad core Cortex-A72 (ARM v8) 64-bit SoC @ 1.5GHz',
    '4GB LPDDR4-3200 SDRAM',
    'True Gigabit Ethernet with PoE Support via separate PoE HAT',
    '2x USB 3.0 SuperSpeed Ports (Blue) + 2x USB 2.0 HighSpeed Ports (Black)',
    'Dual Micro-HDMI display outputs supporting up to 4Kp60 resolution',
    'USB-C Power Input (5V / 3.0A recommended)',
    'Standard 40-pin GPIO Header (28 GPIOs with I2C, SPI, UART, PWM)',
  ],
  subcomponents: [
    {
      id: 'sub_rpi_soc',
      name: 'Broadcom BCM2711 Application Processor',
      category: 'ic',
      partNumber: 'BCM2711ZPKFSB01C0T',
      manufacturer: 'Broadcom Inc.',
      description: '64-bit Quad-Core ARM Cortex-A72 processor @ 1.5GHz with VideoCore VI 3D GPU and aluminum heat lid.',
      status: 'nominal',
      specifications: { cores: 4, arch: 'ARMv8-A 64-bit', clockGhz: 1.5, processNm: 28 },
    },
    {
      id: 'sub_rpi_ram',
      name: '4GB LPDDR4 High-Speed RAM',
      category: 'ic',
      partNumber: 'D9ZCL / SEC 4GB LPDDR4',
      manufacturer: 'Micron / Samsung',
      description: '3200 MT/s Low-Power DDR4 Synchronous DRAM memory seated directly adjacent to the main SoC.',
      status: 'nominal',
      specifications: { capacityGb: 4, speedMt: 3200, type: 'LPDDR4' },
    },
    {
      id: 'sub_rpi_eth',
      name: 'Gigabit Ethernet Controller & RJ45 Jack',
      category: 'connector',
      partNumber: 'BCM54213PE + MagJack',
      manufacturer: 'Broadcom / Pulse',
      description: 'Single-port Gigabit Ethernet PHY with internal magnetics and dual activity/link indicator LEDs.',
      status: 'nominal',
      specifications: { speed: '10/100/1000 Mbps', poeHeader: '4-pin ready' },
    },
    {
      id: 'sub_rpi_usb3_hub',
      name: 'USB 3.0 PCIe Host Controller',
      category: 'ic',
      partNumber: 'VL805-Q6',
      manufacturer: 'VIA Labs Inc.',
      description: 'SuperSpeed USB 3.0 xHCI host controller connected via single-lane PCIe 2.0 bus to the SoC.',
      status: 'nominal',
      specifications: { ports: 4, bandwidth: '5 Gbps SuperSpeed' },
    },
    {
      id: 'sub_rpi_usb_c_pwr',
      name: 'USB-C Power Delivery Jack',
      category: 'connector',
      partNumber: 'TYPE-C-16P-SMD',
      manufacturer: 'Amphenol ICC',
      description: 'Reversible USB Type-C receptacle with dual 5.1k pull-down CC resistors dedicated to 5V 3A input.',
      status: 'nominal',
      specifications: { inputRating: '5.1V 3.0A DC', connection: 'Power Only' },
    },
    {
      id: 'sub_rpi_mhdmi',
      name: 'Dual Micro-HDMI Video Ports',
      category: 'connector',
      partNumber: 'HDMI-MICRO-TypeD-x2',
      manufacturer: 'Molex',
      description: 'Dual Type-D Micro-HDMI sockets delivering dual simultaneous display output up to 4K 60fps.',
      status: 'nominal',
      specifications: { channels: 2, resolutionMax: '3840x2160 @ 60Hz' },
    },
    {
      id: 'sub_rpi_gpio_40',
      name: '40-Pin 2.54mm GPIO Header Strip',
      category: 'connector',
      partNumber: '2x20 Male Pin Header',
      manufacturer: 'Wurth Elektronik',
      description: 'Standard Raspberry Pi 40-pin header offering 28 GPIO pins with SPI, I2C, UART, and PWM lines.',
      status: 'nominal',
      specifications: { pinCount: 40, pitchMm: 2.54, currentPerPinMa: 16 },
    },
    {
      id: 'sub_rpi_microsd',
      name: 'MicroSD Card Socket',
      category: 'connector',
      partNumber: 'TF-PUSH-PULL',
      manufacturer: 'Molex',
      description: 'High-speed UHS-I MicroSD push-pull card socket mounted on the bottom side of the PCB.',
      status: 'nominal',
      specifications: { bus: 'SDIO 4-bit UHS-I', mode: 'SDR50' },
    },
  ],
};

// 4. DOCUMENTED REAL DRONE PLATFORM: MARK4 5" FPV FREESTYLE QUADCOPTER
export const DronePlatformSpecification: HardwareSpecification = {
  modelNumber: 'MARK4-FPV-5INCH',
  manufacturer: 'GEPRC / Betaflight Community',
  revision: 'Mark4 Freestyle V2',
  datasheetUrl: 'https://betaflight.com/docs/wiki/getting-started',
  dimensions: {
    widthMm: 225.0,
    heightMm: 45.0,
    depthMm: 225.0,
    massGrams: 365.0,
    mountingHolePitchMm: '30.5 x 30.5 mm & 20 x 20 mm FC/ESC Stack',
  },
  electrical: {
    operatingVoltage: '14.8V DC (4S LiPo) / 22.2V DC (6S LiPo)',
    minVoltage: 13.2,
    maxVoltage: 25.2,
    logicLevel: '3.3V Logic / DShot600 Digital Protocol',
    quiescentCurrentMa: 280,
    maxCurrentDrawMa: 160000,
    powerRatingWatts: 2400.0,
  },
  protocols: ['DShot600', 'CRSF / ExpressLRS 2.4GHz', 'Betaflight MSP', 'NMEA / UBX GPS', 'SmartAudio / Tramp VTX', 'Analog NTSC/PAL Video'],
  mechanicalMounts: ['M3 Motor Mount Pattern (16x16mm / 19x19mm)', '30.5x30.5mm Isolation Grommet Stack', '19mm Micro FPV Camera Mount'],
  features: [
    'True-X Geometry 225mm Wheelbase 3K Carbon Fiber Airframe with 5mm Chamfered Arms',
    '4x BrotherHobby / EMAX ECO II 2207 2400KV High-Torque Brushless DC Motors',
    'Holybro / SpeedyBee 45A BLHeli_S DShot600 4-in-1 ESC with 35V 1000uF Low-ESR Capacitor',
    'SpeedyBee F405 V3 Flight Controller (STM32F405 MCU, ICM-42688-P Gyro/Accelerometer)',
    'Matek Systems M8Q-5883 High-Precision GPS & Compass Module on 30° TPU Mast',
    'ExpressLRS (ELRS) 2.4GHz Nano Diversity Receiver with Dual Dipole T-Antenna',
    'Caddx Ratel 2 1200TVL Starlight Low-Light Micro FPV Camera with Red TPU Mount',
    'HQProp DP5X4.3X3V1S 5043 3-Blade Polycarbonate Propellers (2x CW, 2x CCW)',
    'AMASS XT60H High-Current Battery Connector with 12AWG Silicone Pigtail Leads',
  ],
  subcomponents: [
    {
      id: 'sub_drone_frame',
      name: 'Mark4 5" Carbon Fiber Airframe',
      category: 'chassis',
      partNumber: 'MARK4-FRAME-5IN',
      manufacturer: 'GEPRC',
      description: '3K matte twill full carbon fiber freestyle airframe featuring 5mm replaceable arms and 7075 red aluminum standoffs.',
      status: 'nominal',
      specifications: { wheelbaseMm: 225, armThicknessMm: 5.0, topPlateMm: 2.0, bottomPlateMm: 2.5 },
    },
    {
      id: 'sub_drone_motor1',
      name: 'Motor 1 (Front Right Brushless DC)',
      category: 'motor',
      partNumber: 'ECO-II-2207-2400KV',
      manufacturer: 'EMAX / BrotherHobby',
      description: 'Brushless outrunner motor with N52SH neodymium arc magnets, high-temp copper windings, and hollow steel shaft.',
      status: 'nominal',
      specifications: { kv: 2400, statorMm: '22x07', maxThrustG: 1450, rotation: 'CW' },
    },
    {
      id: 'sub_drone_motor2',
      name: 'Motor 2 (Front Left Brushless DC)',
      category: 'motor',
      partNumber: 'ECO-II-2207-2400KV',
      manufacturer: 'EMAX / BrotherHobby',
      description: 'Brushless outrunner motor with N52SH neodymium arc magnets, high-temp copper windings, and hollow steel shaft.',
      status: 'nominal',
      specifications: { kv: 2400, statorMm: '22x07', maxThrustG: 1450, rotation: 'CCW' },
    },
    {
      id: 'sub_drone_motor3',
      name: 'Motor 3 (Rear Left Brushless DC)',
      category: 'motor',
      partNumber: 'ECO-II-2207-2400KV',
      manufacturer: 'EMAX / BrotherHobby',
      description: 'Brushless outrunner motor with N52SH neodymium arc magnets, high-temp copper windings, and hollow steel shaft.',
      status: 'nominal',
      specifications: { kv: 2400, statorMm: '22x07', maxThrustG: 1450, rotation: 'CW' },
    },
    {
      id: 'sub_drone_motor4',
      name: 'Motor 4 (Rear Right Brushless DC)',
      category: 'motor',
      partNumber: 'ECO-II-2207-2400KV',
      manufacturer: 'EMAX / BrotherHobby',
      description: 'Brushless outrunner motor with N52SH neodymium arc magnets, high-temp copper windings, and hollow steel shaft.',
      status: 'nominal',
      specifications: { kv: 2400, statorMm: '22x07', maxThrustG: 1450, rotation: 'CCW' },
    },
    {
      id: 'sub_drone_prop1',
      name: 'Propeller 1 (Front Right 3-Blade Airfoil)',
      category: 'propeller',
      partNumber: 'HQ-DP5X4.3X3V1S-CW',
      manufacturer: 'HQProp',
      description: '5.0-inch diameter x 4.3-inch pitch 3-blade polycarbonate airfoil prop with M5 nylon lock nut.',
      status: 'nominal',
      specifications: { diameterInches: 5.0, pitchInches: 4.3, blades: 3, direction: 'CW' },
    },
    {
      id: 'sub_drone_prop2',
      name: 'Propeller 2 (Front Left 3-Blade Airfoil)',
      category: 'propeller',
      partNumber: 'HQ-DP5X4.3X3V1S-CCW',
      manufacturer: 'HQProp',
      description: '5.0-inch diameter x 4.3-inch pitch 3-blade polycarbonate airfoil prop with M5 nylon lock nut.',
      status: 'nominal',
      specifications: { diameterInches: 5.0, pitchInches: 4.3, blades: 3, direction: 'CCW' },
    },
    {
      id: 'sub_drone_prop3',
      name: 'Propeller 3 (Rear Left 3-Blade Airfoil)',
      category: 'propeller',
      partNumber: 'HQ-DP5X4.3X3V1S-CW',
      manufacturer: 'HQProp',
      description: '5.0-inch diameter x 4.3-inch pitch 3-blade polycarbonate airfoil prop with M5 nylon lock nut.',
      status: 'nominal',
      specifications: { diameterInches: 5.0, pitchInches: 4.3, blades: 3, direction: 'CW' },
    },
    {
      id: 'sub_drone_prop4',
      name: 'Propeller 4 (Rear Right 3-Blade Airfoil)',
      category: 'propeller',
      partNumber: 'HQ-DP5X4.3X3V1S-CCW',
      manufacturer: 'HQProp',
      description: '5.0-inch diameter x 4.3-inch pitch 3-blade polycarbonate airfoil prop with M5 nylon lock nut.',
      status: 'nominal',
      specifications: { diameterInches: 5.0, pitchInches: 4.3, blades: 3, direction: 'CCW' },
    },
    {
      id: 'sub_drone_esc',
      name: '4-in-1 45A BLHeli_S Electronic Speed Controller',
      category: 'esc',
      partNumber: 'SPEEDYBEE-45A-4IN1',
      manufacturer: 'SpeedyBee',
      description: '4-in-1 multi-rotor ESC running BLHeli_S firmware with 3-phase MOSFET bridges and DShot600 telemetry.',
      status: 'nominal',
      specifications: { continuousCurrentA: 45, burstCurrentA: 55, protocol: 'DShot600', input: '3-6S LiPo' },
    },
    {
      id: 'sub_drone_fc',
      name: 'SpeedyBee F405 V3 Flight Controller',
      category: 'ic',
      partNumber: 'SPEEDYBEE-F405-V3',
      manufacturer: 'SpeedyBee',
      description: 'High-performance flight controller featuring STM32F405 MCU @ 168MHz, ICM-42688-P 6-axis gyro, and Betaflight OSD.',
      status: 'nominal',
      specifications: { mcu: 'STM32F405 @ 168MHz', gyro: 'ICM-42688-P 6-DOF', osd: 'AT7456E', uarts: 5 },
    },
    {
      id: 'sub_drone_gps',
      name: 'Matek M8Q-5883 GPS & Compass Module',
      category: 'sensor',
      partNumber: 'M8Q-5883',
      manufacturer: 'Matek Systems',
      description: 'u-blox SAM-M8Q GNSS concurrent receiver engine with integrated QMC5883L magnetic compass on 30° TPU mast.',
      status: 'nominal',
      specifications: { gnss: 'GPS / GLONASS / Galileo', updateRateHz: 10, patchMm: '15x15' },
    },
    {
      id: 'sub_drone_rx',
      name: 'ExpressLRS 2.4GHz Nano Radio Receiver',
      category: 'radio',
      partNumber: 'BETAFPV-ELRS-2.4G',
      manufacturer: 'BETAFPV / ExpressLRS',
      description: 'Ultra-low latency 2.4GHz radio link receiver with ceramic dipole T-antenna running open-source ExpressLRS.',
      status: 'nominal',
      specifications: { frequencyGhz: 2.4, packetRateHz: 500, telemetryMw: 100 },
    },
    {
      id: 'sub_drone_camera',
      name: 'Caddx Ratel 2 1200TVL FPV Camera',
      category: 'optical',
      partNumber: 'CADDX-RATEL2-RED',
      manufacturer: 'Caddx FPGA',
      description: 'Micro FPV camera with 1/1.8" starlight HDR sensor, 2.1mm optical glass lens, and red TPU vibration isolation mount.',
      status: 'nominal',
      specifications: { resolutionTvl: 1200, fovDeg: 165, minLux: 0.0001, latencyMs: 8 },
    },
    {
      id: 'sub_drone_cap',
      name: '35V 1000uF Low-ESR Electrolytic Capacitor',
      category: 'passive',
      partNumber: 'RUBYCON-ZLH-35V-1000UF',
      manufacturer: 'Rubycon',
      description: 'Ultra-low impedance aluminum electrolytic filter capacitor suppressing motor inductive voltage spikes.',
      status: 'nominal',
      specifications: { capacitanceUf: 1000, voltageMaxV: 35, esrOhm: 0.015 },
    },
    {
      id: 'sub_drone_xt60',
      name: 'AMASS XT60H Female Power Harness',
      category: 'connector',
      partNumber: 'AMASS-XT60H-F',
      manufacturer: 'AMASS',
      description: 'Gold-plated high-amperage coaxial power plug with heat-resistant nylon body and 12AWG flexible silicone wire.',
      status: 'nominal',
      specifications: { maxCurrentA: 60, wireGaugeAwg: 12 },
    },
  ],
};

// 5. 3S 2200mAh LiPo BATTERY PACK
export const LiPoBatterySpecification: HardwareSpecification = {
  modelNumber: 'TA-45C-2200-3S1P',
  manufacturer: 'Tattu / Gens Ace',
  revision: 'V3 High Discharge',
  datasheetUrl: 'https://gensace.de/tattu-2200mah-11-1v-45c-3s1p-lipo-battery-pack-with-xt60-plug.html',
  dimensions: {
    widthMm: 34.0,
    heightMm: 24.0,
    depthMm: 106.0,
    massGrams: 175.0,
    mountingHolePitchMm: 'Hook-and-Loop (Velcro) Battery Strap Mounting',
  },
  electrical: {
    operatingVoltage: '11.1V DC (Nominal) / 12.6V DC (Fully Charged)',
    minVoltage: 9.6,
    maxVoltage: 12.6,
    logicLevel: 'Analog High-Current Power',
    quiescentCurrentMa: 0,
    maxCurrentDrawMa: 99000,
    powerRatingWatts: 1098.9,
  },
  protocols: ['High-Amperage DC Discharge', 'JST-XH Cell Voltage Sensing'],
  mechanicalMounts: ['Silicone Battery Anti-Slip Pad & Dual Reinforced Kevlar Straps'],
  features: [
    '3S1P Configuration: 3 High-Energy-Density Lithium Polymer Pouch Cells in Series',
    '2200 mAh Rated Storage Capacity (24.42 Watt-hours)',
    '45C Continuous Discharge Rate (99 Amps Continuous, 90C Burst)',
    'Gold-Plated AMASS XT60 Connector on 12AWG Ultra-Flexible Silicone Wire',
    'JST-XH 4-Pin Individual Cell Balance Connector for Precision BMS Balancing',
  ],
  subcomponents: [
    {
      id: 'sub_lipo_cells',
      name: '3x Series LiPo Pouch Cells',
      category: 'power',
      partNumber: 'LIPO-CELL-3.7V-2200',
      manufacturer: 'Tattu',
      description: '3 stacked sealed aluminum laminate lithium polymer cells providing 3.7V nominal (4.2V peak) per cell.',
      status: 'nominal',
      specifications: { chemistry: 'LiCoO2 / NMC', nominalVoltage: 11.1, capacityMah: 2200 },
    },
    {
      id: 'sub_lipo_xt60',
      name: 'XT60 Male Discharge Plug',
      category: 'connector',
      partNumber: 'AMASS-XT60-M',
      manufacturer: 'AMASS',
      description: 'High-amperage gold-plated brass bullet contacts inside high-temperature yellow nylon housing.',
      status: 'nominal',
      specifications: { continuousA: 60, peakA: 100 },
    },
    {
      id: 'sub_lipo_jst',
      name: 'JST-XH 4-Pin Balance Connector',
      category: 'connector',
      partNumber: 'JST-XH-04P',
      manufacturer: 'J.S.T. Mfg. Co.',
      description: '2.50mm pitch natural white nylon balance connector tapping each individual cell node.',
      status: 'nominal',
      specifications: { pinCount: 4, pitchMm: 2.5 },
    },
    {
      id: 'sub_lipo_wrap',
      name: 'Flame-Retardant PVC Heat Shrink',
      category: 'chassis',
      partNumber: 'PVC-SHRINK-YELLOW',
      manufacturer: 'Tattu',
      description: 'Puncture-resistant outer insulating wrap protecting pouch cells from mechanical damage.',
      status: 'nominal',
    },
  ],
};

// 6. HC-SR04 ULTRASONIC SENSOR
export const UltrasonicSensorSpecification: HardwareSpecification = {
  modelNumber: 'HC-SR04',
  manufacturer: 'Cytron / SparkFun',
  revision: 'V2.0',
  datasheetUrl: 'https://www.sparkfun.com/datasheets/Sensors/Proximity/HCSR04.pdf',
  dimensions: {
    widthMm: 45.0,
    heightMm: 20.0,
    depthMm: 15.0,
    massGrams: 8.5,
    mountingHolePitchMm: 'Dual M2 Mounting Flanges',
  },
  electrical: {
    operatingVoltage: '5V DC',
    minVoltage: 4.5,
    maxVoltage: 5.5,
    logicLevel: '5V TTL',
    quiescentCurrentMa: 2,
    maxCurrentDrawMa: 15,
    powerRatingWatts: 0.075,
  },
  protocols: ['Pulse-Width Modulated Echo Timing (10us Trigger)'],
  mechanicalMounts: ['Dual Ultrasonic Transducer Cylinders (16mm Diameter)'],
  features: [
    'Operating Frequency: 40 kHz Acoustic Ultrasonic Burst',
    'Effective Measurement Range: 2 cm to 400 cm (accuracy ±3 mm)',
    'Measuring Angle: 15 degrees effective cone',
    'Simple 4-Pin 2.54mm Interface: VCC, Trigger, Echo, GND',
  ],
  subcomponents: [
    {
      id: 'sub_us_tx',
      name: '40 kHz Piezoelectric Ultrasonic Transmitter (T)',
      category: 'sensor',
      partNumber: 'TCT40-16T',
      manufacturer: 'Audiowell',
      description: '16mm aluminum canister with resonant piezoelectric crystal emitting 8-cycle 40kHz sonic burst.',
      status: 'nominal',
      specifications: { frequencyKhz: 40, diameterMm: 16 },
    },
    {
      id: 'sub_us_rx',
      name: '40 kHz Piezoelectric Ultrasonic Receiver (R)',
      category: 'sensor',
      partNumber: 'TCT40-16R',
      manufacturer: 'Audiowell',
      description: '16mm acoustic sensor receiving the reflected ultrasonic echo wave and converting to microvolt electrical signal.',
      status: 'nominal',
      specifications: { frequencyKhz: 40, sensitivityDb: -65 },
    },
    {
      id: 'sub_us_opamp',
      name: 'Quad Operational Amplifier IC',
      category: 'ic',
      partNumber: 'LM324 / MAX232',
      manufacturer: 'Texas Instruments',
      description: 'Quad differential operational amplifiers handling echo signal amplification and threshold hysteresis.',
      status: 'nominal',
    },
  ],
};

// 7. SG90 MICRO SERVO MOTOR
export const SG90ServoSpecification: HardwareSpecification = {
  modelNumber: 'SG90',
  manufacturer: 'TowerPro',
  revision: 'Rev B',
  datasheetUrl: 'http://www.ee.ic.ac.uk/pcheung/teaching/DE1_EE/stores/sg90_datasheet.pdf',
  dimensions: {
    widthMm: 22.2,
    heightMm: 31.0,
    depthMm: 11.8,
    massGrams: 9.0,
    mountingHolePitchMm: '28.0 mm (Dual M2 Mounting Tabs)',
  },
  electrical: {
    operatingVoltage: '4.8V - 6.0V DC',
    minVoltage: 4.5,
    maxVoltage: 6.0,
    logicLevel: '3.3V - 5V PWM (50Hz / 20ms frame)',
    quiescentCurrentMa: 10,
    maxCurrentDrawMa: 650,
    powerRatingWatts: 3.25,
  },
  protocols: ['Analog PWM Servo Pulse (1.0ms - 2.0ms duty cycle)'],
  mechanicalMounts: ['Dual Lateral Screw Mounting Ears', 'Output Spline with Single/Double Horns'],
  features: [
    'Stall Torque: 1.8 kg·cm (at 4.8V) / 2.5 kg·cm (at 6.0V)',
    'Operating Speed: 0.12 sec / 60 degrees (at 4.8V)',
    'Rotational Range: 180 degrees (±90 degrees from center)',
    'Dead Band Width: 7 microseconds',
    '3-Pin DuPont Connector: Brown (GND), Red (VCC 5V), Orange (PWM Signal)',
  ],
  subcomponents: [
    {
      id: 'sub_servo_motor',
      name: 'Coreless Miniature DC Motor',
      category: 'motor',
      partNumber: 'CORELESS-0816',
      manufacturer: 'TowerPro',
      description: 'High-speed miniature coreless DC brush motor driving the reduction gear train.',
      status: 'nominal',
    },
    {
      id: 'sub_servo_gears',
      name: '5-Stage POM Reduction Gearset',
      category: 'chassis',
      partNumber: 'GEARS-POM-5STAGE',
      manufacturer: 'TowerPro',
      description: 'Precision molded polyoxymethylene (POM) mechanical gear train providing 300:1 torque multiplication.',
      status: 'nominal',
      specifications: { ratio: '300:1', material: 'POM plastic' },
    },
    {
      id: 'sub_servo_pot',
      name: 'Position Feedback Potentiometer',
      category: 'sensor',
      partNumber: 'POT-10K-ROTARY',
      manufacturer: 'Noble',
      description: 'Closed-loop 10k rotary potentiometer mechanically coupled to the output shaft for position telemetry.',
      status: 'nominal',
    },
    {
      id: 'sub_servo_arm',
      name: 'Nylon Output Horn & Spline',
      category: 'control',
      partNumber: 'HORN-NYLON-CROSS',
      manufacturer: 'TowerPro',
      description: 'Removable 21-tooth nylon horn arm fastened by an M2 stainless steel center retainer screw.',
      status: 'nominal',
    },
  ],
};

// 8. 130 DC HOBBY MOTOR
export const DCMotorSpecification: HardwareSpecification = {
  modelNumber: 'TYPE-130-DC',
  manufacturer: 'Mabuchi / Adafruit',
  revision: 'Standard 130',
  dimensions: {
    widthMm: 20.0,
    heightMm: 15.0,
    depthMm: 38.0,
    massGrams: 17.5,
    mountingHolePitchMm: '10.0 mm (2x M2 Front Face)',
  },
  electrical: {
    operatingVoltage: '3.0V - 6.0V DC',
    minVoltage: 1.5,
    maxVoltage: 9.0,
    logicLevel: 'DC Direct / PWM H-Bridge Driver',
    quiescentCurrentMa: 150,
    maxCurrentDrawMa: 1200,
    powerRatingWatts: 6.0,
  },
  protocols: ['Direct DC Polarity Inversion (Bi-directional) / PWM Speed Control'],
  mechanicalMounts: ['Dual M2 Face Mount Screws', '2mm Precision Steel Output Shaft'],
  features: [
    'No-load Speed: 9100 RPM @ 3.0V, 15000 RPM @ 6.0V',
    'Permanent Magnet Stator with Double Flat Housing Profile',
    '3-Pole Rotor Armature with Commutator and Dual Solder Eyelets',
  ],
  subcomponents: [
    {
      id: 'sub_dc_armature',
      name: '3-Slot Wound Rotor Armature',
      category: 'motor',
      partNumber: 'ARMATURE-3SLOT',
      manufacturer: 'Mabuchi',
      description: 'Enameled copper wire windings on laminated iron rotor core providing rotating magnetic poles.',
      status: 'nominal',
    },
    {
      id: 'sub_dc_magnets',
      name: 'Dual Permanent Ferrite Magnets',
      category: 'passive',
      partNumber: 'FERRITE-STATOR-ARC',
      manufacturer: 'Mabuchi',
      description: 'Arc-shaped ceramic ferrite permanent magnets fixed to the inner zinc-plated steel housing.',
      status: 'nominal',
    },
    {
      id: 'sub_dc_shaft',
      name: '2.0mm Hardened Steel Shaft',
      category: 'chassis',
      partNumber: 'SHAFT-STEEL-2MM',
      manufacturer: 'Mabuchi',
      description: 'Ground precision steel drive shaft extending 9mm forward to accept gears, pulleys, or wheels.',
      status: 'nominal',
      specifications: { diameterMm: 2.0, extensionMm: 9.0 },
    },
  ],
};

// 9. SOLDERLESS BREADBOARD (HALF-SIZE 400 TIE POINTS)
export const BreadboardSpecification: HardwareSpecification = {
  modelNumber: 'BB-400-TIE',
  manufacturer: 'BusBoard / SparkFun',
  revision: 'Half-Size 400',
  dimensions: {
    widthMm: 82.0,
    heightMm: 9.5,
    depthMm: 55.0,
    massGrams: 42.0,
    mountingHolePitchMm: 'Peel-and-Stick Adhesive Backing / Interlocking Tabs',
  },
  electrical: {
    operatingVoltage: 'Up to 36V DC',
    minVoltage: 0,
    maxVoltage: 50,
    logicLevel: 'Passive Bus',
    quiescentCurrentMa: 0,
    maxCurrentDrawMa: 2500,
    powerRatingWatts: 75.0,
  },
  protocols: ['Passive 2.54mm Solderless Prototyping Grid'],
  mechanicalMounts: ['Dovetail Interlocking Tabs on all 4 sides', 'Foam Adhesive Underlayment'],
  features: [
    '300 Terminal Tie Points (30 columns x 2 sets of 5-pin interconnected rows A-E and F-J)',
    '100 Power Bus Distribution Points (4 separate continuous distribution rails marked with Red/Blue silkscreen)',
    'Standard 0.1 inch (2.54 mm) Contact Hole Pitch',
    'Center trough (0.3 inch spacing) perfectly sized for standard Dual In-line Package (DIP) ICs',
    'Nickel-plated phosphor bronze dual spring wipe contacts (accepts 21 to 26 AWG wire)',
  ],
  subcomponents: [
    {
      id: 'sub_bb_housing',
      name: 'Molded ABS Plastic Body',
      category: 'chassis',
      partNumber: 'ABS-HOUSING-WHITE',
      manufacturer: 'BusBoard',
      description: 'Impact-resistant white ABS housing with molded row letters (A-J), column numbers (1-30), and rail strips.',
      status: 'nominal',
    },
    {
      id: 'sub_bb_clips',
      name: 'Phosphor Bronze Spring Clip Strips',
      category: 'connector',
      partNumber: 'CLIPS-PB-5PIN-x60',
      manufacturer: 'BusBoard',
      description: '60 independent 5-point tie clips and 4 power rail strips offering reliable retention across 50,000 insertions.',
      status: 'nominal',
      specifications: { contactMetal: 'Phosphor Bronze', plating: 'Nickel', wireAwg: '21-26' },
    },
  ],
};

// 10. OLED 0.96" SSD1306 MONOCHROME I2C DISPLAY
export const OLED096Specification: HardwareSpecification = {
  modelNumber: 'SSD1306-0.96-I2C',
  manufacturer: 'Solomon Systech / Generic Maker',
  revision: 'V2.1 4-Pin',
  datasheetUrl: 'https://cdn-shop.adafruit.com/datasheets/SSD1306.pdf',
  dimensions: {
    widthMm: 27.3,
    heightMm: 4.1,
    depthMm: 27.8,
    massGrams: 4.0,
    mountingHolePitchMm: '23.7 x 23.7 mm (4x M2)',
  },
  electrical: {
    operatingVoltage: '3.3V - 5.0V DC (Built-in LDO & Charge Pump)',
    minVoltage: 3.0,
    maxVoltage: 5.5,
    logicLevel: '3.3V / 5V Compatible',
    quiescentCurrentMa: 0.05,
    maxCurrentDrawMa: 25.0,
    powerRatingWatts: 0.12,
  },
  protocols: ['I2C (Fast Mode 400kHz)', 'Address: 0x3C or 0x3D'],
  mechanicalMounts: ['4x M2 Through-Hole Corner Mounts', '4-Pin 2.54mm Header (VCC, GND, SCL, SDA)'],
  features: [
    'Resolution: 128 x 64 pixels (Monochrome self-illuminating PMOLED)',
    'High Contrast Ratio: > 10,000:1 with true pitch-black background',
    'Ultra-wide viewing angle: > 160 degrees without color shift',
    'Internal charge pump generates 7.5V OLED drive voltage from 3.3V rail',
    'Standard I2C interface requiring only 2 data lines (SDA, SCL)',
  ],
  subcomponents: [
    {
      id: 'sub_oled_glass',
      name: '0.96" PMOLED Display Glass Panel',
      category: 'passive',
      partNumber: 'UG-2864HSWEG01',
      manufacturer: 'WiseChip Semiconductor',
      description: 'Thin organic light emitting diode matrix panel with integrated polyimide chip-on-glass (COG) ribbon.',
      status: 'nominal',
      specifications: { resolution: '128x64', activeAreaMm: '21.74 x 10.86', color: 'Electric Blue / White' },
    },
    {
      id: 'sub_oled_ic',
      name: 'SSD1306 Display Controller & RAM',
      category: 'ic',
      partNumber: 'SSD1306-COG',
      manufacturer: 'Solomon Systech',
      description: 'Single-chip CMOS OLED/PLED driver with 128x64 bits Graphic Display Data RAM (GDDRAM).',
      status: 'nominal',
      specifications: { ramBytes: 1024, maxI2cFreqKhz: 400 },
    },
    {
      id: 'sub_oled_ldo',
      name: '3.3V Ultra-Low-Dropout Regulator',
      category: 'power',
      partNumber: 'XC6206P332MR',
      manufacturer: 'Torex Semiconductor',
      description: 'SOT-23 voltage regulator ensuring safe logic levels when powered by 5V Arduino boards.',
      status: 'nominal',
      specifications: { outputVoltage: 3.3, maxCurrentMa: 200 },
    },
  ],
};

// 11. LCD 1602 WITH I2C PCF8574 BACKPACK
export const LCD1602Specification: HardwareSpecification = {
  modelNumber: '1602A-I2C-BLUE',
  manufacturer: 'Hitachi / NXP Backpack',
  revision: 'Rev 1.3 Backpack',
  datasheetUrl: 'https://www.sparkfun.com/datasheets/LCD/HD44780.pdf',
  dimensions: {
    widthMm: 80.0,
    heightMm: 12.0,
    depthMm: 36.0,
    massGrams: 35.0,
    mountingHolePitchMm: '75.0 x 31.0 mm (4x M3)',
  },
  electrical: {
    operatingVoltage: '5.0V DC',
    minVoltage: 4.5,
    maxVoltage: 5.5,
    logicLevel: '5V TTL',
    quiescentCurrentMa: 1.5,
    maxCurrentDrawMa: 55.0, // Backlight LED on
    powerRatingWatts: 0.28,
  },
  protocols: ['I2C (Standard Mode 100kHz)', 'Address: 0x27 or 0x3F via A0/A1/A2 solder jumpers'],
  mechanicalMounts: ['4x M3 Corner Mounting Screws', 'Right-angle 4-Pin 2.54mm I2C Header'],
  features: [
    'Display format: 16 characters x 2 lines (32 characters total)',
    'Character font: 5 x 8 dot matrix with cursor support',
    'High-efficiency LED backlight (Transflective blue screen with crisp white text)',
    'Integrated contrast potentiometer trimmer on backpack rear',
    'PCF8574 8-bit I/O expander eliminates 10 GPIO connections to MCU',
  ],
  subcomponents: [
    {
      id: 'sub_lcd_panel',
      name: '16x2 STN Liquid Crystal Glass Panel',
      category: 'passive',
      partNumber: 'TC1602A-01T',
      manufacturer: 'Tianma Microelectronics',
      description: 'Twisted nematic liquid crystal display with metal bezel retaining frame and elastomer zebra connector.',
      status: 'nominal',
      specifications: { characters: '16x2', charSizeMm: '2.95 x 4.35', backlight: 'Blue LED' },
    },
    {
      id: 'sub_lcd_controller',
      name: 'HD44780 Dot Matrix Controller LSI',
      category: 'ic',
      partNumber: 'HD44780U-A00',
      manufacturer: 'Hitachi',
      description: 'Industry-standard character generator ROM and display RAM controller chip.',
      status: 'nominal',
      specifications: { romChars: 208, ramChars: 8 },
    },
    {
      id: 'sub_lcd_expander',
      name: 'PCF8574T Remote 8-Bit I/O Expander',
      category: 'ic',
      partNumber: 'PCF8574T',
      manufacturer: 'NXP Semiconductors',
      description: 'Translates 2-wire I2C serial bus commands into 4-bit parallel HD44780 control signals.',
      status: 'nominal',
      specifications: { package: 'SOIC-16', i2cSpeed: '100 kHz' },
    },
  ],
};

// 12. TFT COLOR DISPLAY 1.3" / 2.4" ST7789 IPS SPI
export const TFTColorScreenSpecification: HardwareSpecification = {
  modelNumber: 'ST7789-240x240-IPS',
  manufacturer: 'Sitronix Technology',
  revision: 'IPS SPI V1.2',
  datasheetUrl: 'https://www.crystalfontz.com/controllers/Sitronix/ST7789V/',
  dimensions: {
    widthMm: 39.2,
    heightMm: 3.2,
    depthMm: 27.8,
    massGrams: 8.5,
    mountingHolePitchMm: '34.0 x 24.0 mm (4x M2)',
  },
  electrical: {
    operatingVoltage: '3.3V - 5V DC',
    minVoltage: 3.0,
    maxVoltage: 5.5,
    logicLevel: '3.3V Logic (5V tolerant with onboard level shifter)',
    quiescentCurrentMa: 2.0,
    maxCurrentDrawMa: 45.0, // Backlight 100%
    powerRatingWatts: 0.22,
  },
  protocols: ['4-Wire High-Speed SPI (Up to 62.5 MHz clock)'],
  mechanicalMounts: ['4x M2 Corner Mounts', '8-Pin 2.54mm Standard Header'],
  features: [
    'Resolution: 240 x 240 True-Color Pixels (65K / 262K RGB colors)',
    'IPS Wide-Angle Technology with full 178-degree viewing cone',
    'PWM Backlight (BLK) pin allows smooth hardware brightness dimming',
    'Ultra-fast frame rate support for live animations, dials, and telemetry graphs',
  ],
  subcomponents: [
    {
      id: 'sub_tft_ips_glass',
      name: '1.3-inch Full Color IPS Glass Panel',
      category: 'passive',
      partNumber: 'IPS-240240-TFT',
      manufacturer: 'BOE Technology',
      description: 'In-Plane Switching liquid crystal display panel with vivid chromatic saturation and black matrix.',
      status: 'nominal',
      specifications: { resolution: '240x240', colorDepth: '16-bit RGB565', activeAreaMm: '23.4 x 23.4' },
    },
    {
      id: 'sub_tft_driver',
      name: 'ST7789V High-Speed Display Driver',
      category: 'ic',
      partNumber: 'ST7789V',
      manufacturer: 'Sitronix',
      description: 'Single-chip controller/driver with 240x320 embedded SRAM supporting hardware vertical scrolling.',
      status: 'nominal',
      specifications: { maxSpiMhz: 62.5, sramBytes: 172800 },
    },
  ],
};

// 13. TM1637 4-DIGIT 7-SEGMENT DISPLAY
export const TM1637DisplaySpecification: HardwareSpecification = {
  modelNumber: 'TM1637-4DIG-RED',
  manufacturer: 'Titan Micro Electronics',
  revision: '0.36" Common Anode',
  datasheetUrl: 'https://datasheet.lcsc.com/lcsc/2103171830_Titan-Micro-Elec-TM1637_C268482.pdf',
  dimensions: {
    widthMm: 42.0,
    heightMm: 11.0,
    depthMm: 24.0,
    massGrams: 14.0,
    mountingHolePitchMm: '38.0 x 20.0 mm (4x M2)',
  },
  electrical: {
    operatingVoltage: '3.3V - 5.0V DC',
    minVoltage: 3.0,
    maxVoltage: 5.5,
    logicLevel: '3.3V / 5V Compatible',
    quiescentCurrentMa: 0.1,
    maxCurrentDrawMa: 80.0, // All 8 segments lit on 4 digits at max duty
    powerRatingWatts: 0.4,
  },
  protocols: ['2-Wire Synchronous Serial (CLK, DIO with I2C-like start/stop protocol)'],
  mechanicalMounts: ['4x M2 Corner Screws', '4-Pin 2.54mm Right-Angle Header'],
  features: [
    '4 Common-Anode 7-Segment LED Digits (0.36 inch character height)',
    'Central colon LED (:) for clock / timecode display',
    '8-step programmable duty cycle brightness control',
    'Only requires 2 microcontroller GPIO pins to drive all 32 LED segments',
  ],
  subcomponents: [
    {
      id: 'sub_tm1637_led_block',
      name: '4-Digit 0.36" Common Anode LED Module',
      category: 'passive',
      partNumber: '3461BS-1',
      manufacturer: 'Kingbright / Generic',
      description: 'High-contrast diffused red epoxy LED 7-segment display with anti-reflective black face.',
      status: 'nominal',
      specifications: { wavelengthNm: 630, forwardVoltageV: 2.0 },
    },
    {
      id: 'sub_tm1637_driver_ic',
      name: 'TM1637 LED Drive Controller IC',
      category: 'ic',
      partNumber: 'TM1637',
      manufacturer: 'Titan Micro Electronics',
      description: 'Dedicated LED scan driver with dynamic keyboard scan circuit and serial interface.',
      status: 'nominal',
      specifications: { package: 'SOP-20', outputCurrentMa: 50 },
    },
  ],
};

// 14. 5.8GHz FPV FIELD MONITOR / DIVERSITY GROUND STATION SCREEN
export const FPVMonitorSpecification: HardwareSpecification = {
  modelNumber: 'FPV-MON-43-DIV',
  manufacturer: 'Hawkeye / Boscam',
  revision: 'Field Pro 4.3"',
  datasheetUrl: 'https://geprc.com/support/datasheets/',
  dimensions: {
    widthMm: 115.0,
    heightMm: 75.0,
    depthMm: 18.0,
    massGrams: 145.0,
    mountingHolePitchMm: 'Standard 1/4-20 UNC Tripod Mount Bushing',
  },
  electrical: {
    operatingVoltage: '7.4V - 16.8V DC (2S-4S LiPo or DC Barrel)',
    minVoltage: 6.5,
    maxVoltage: 18.0,
    logicLevel: 'NTSC / PAL 1.0 Vp-p 75 Ohm Composite',
    quiescentCurrentMa: 20,
    maxCurrentDrawMa: 450,
    powerRatingWatts: 4.8,
  },
  protocols: ['5.8GHz 48-Channel A/B/E/F/R/L Raceband RF Receiver', 'CVBS Video In'],
  mechanicalMounts: ['1/4"-20 Threaded Brass Tripod Socket', 'Foldable Sunshade Hood Latches', 'SMA Antenna Port'],
  features: [
    '4.3-inch High-Brightness (500 cd/m2) Sunlight-Readable LCD Screen',
    'Built-in 48-Channel 5.8GHz diversity receiver with auto-search scanner',
    'Real-time Betaflight OSD overlay: Artificial Horizon, Battery Sag, Flight Mode, GPS, RSSI',
    'No blue-screen blackout policy: renders analog static gracefully on marginal signals',
    'Integrated 1S 18650 Li-ion battery bay and DC 12V barrel charging input',
  ],
  subcomponents: [
    {
      id: 'sub_fpv_lcd',
      name: '4.3" High-Nits TFT LCD Panel',
      category: 'passive',
      partNumber: 'AT043TN24',
      manufacturer: 'Innolux',
      description: '800 x 480 widescreen color display with anti-glare polarizer and LED backlight array.',
      status: 'nominal',
      specifications: { resolution: '800x480', brightnessNits: 500 },
    },
    {
      id: 'sub_fpv_rf_rx',
      name: '5.8GHz Diversity RF Receiver Module',
      category: 'radio',
      partNumber: 'RX5808-DIV',
      manufacturer: 'RichWave',
      description: 'Dual RTC6705 FM demodulator modules providing seamless antenna selection diversity.',
      status: 'nominal',
      specifications: { channels: 48, sensitivityDbm: -92 },
    },
    {
      id: 'sub_fpv_sunshade',
      name: 'Collapsible Matte Black Sunshade Hood',
      category: 'chassis',
      partNumber: 'HOOD-43-FOLD',
      manufacturer: 'Hawkeye',
      description: 'Three-leaf folding sunshade with magnetic latch ensuring high outdoor contrast.',
      status: 'nominal',
    },
  ],
};

// 12. ELECTROLYTIC CAPACITOR (100uF 25V)
export const CapacitorSpecification: HardwareSpecification = {
  modelNumber: 'UVR1E101MDD',
  manufacturer: 'Nichicon / Panasonic',
  revision: 'VR Series Radial',
  datasheetUrl: 'https://www.nichicon.co.jp/english/products/pdfs/e-vr.pdf',
  dimensions: {
    widthMm: 6.3,
    heightMm: 11.0,
    depthMm: 6.3,
    massGrams: 0.8,
    mountingHolePitchMm: '2.5mm Lead Pitch (Breadboard Compatible)',
  },
  electrical: {
    operatingVoltage: 'Up to 25V DC',
    minVoltage: 0.0,
    maxVoltage: 25.0,
    logicLevel: 'Analog Passive Filtering',
    quiescentCurrentMa: 0,
    maxCurrentDrawMa: 180,
    powerRatingWatts: 0.25,
  },
  protocols: ['DC Decoupling', 'AC Ripple Smoothing', 'Energy Storage'],
  mechanicalMounts: ['Through-Hole Radial Leads (2.5mm Pitch)'],
  features: [
    '100 µF Nominal Capacitance with ±20% Tolerance',
    '25V DC Maximum Working Voltage Rating (32V Surge)',
    'Low Equivalent Series Resistance (ESR) for Ripple Rejection',
    'Safety pressure relief vent scored into aluminum top',
    'Standard 2.54mm breadboard pitch compatible wire leads',
  ],
  subcomponents: [
    {
      id: 'sub_cap_can',
      name: 'Aluminum Cylindrical Case & Rubber Bung',
      category: 'chassis',
      partNumber: 'AL-CAN-6X11',
      manufacturer: 'Nichicon',
      description: 'Extruded aluminum can with cross-scored safety relief vent and EPDM rubber bung seal.',
      status: 'nominal',
      specifications: { diameterMm: 6.3, heightMm: 11.0, sleeve: 'Blue PVC' },
    },
    {
      id: 'sub_cap_foil',
      name: 'Etched Aluminum Foil & Electrolyte Separator',
      category: 'passive',
      partNumber: 'ANODE-FOIL-25V',
      manufacturer: 'Nichicon',
      description: 'High-purity etched aluminum oxide dielectric layer immersed in liquid electrolyte.',
      status: 'nominal',
      specifications: { capacitanceUf: 100, tolerancePercent: 20, maxTempC: 85 },
    },
  ],
};

// 13. CERAMIC DISC CAPACITOR (100nF 50V)
export const CeramicCapacitorSpecification: HardwareSpecification = {
  modelNumber: 'K104K15X7RF53L2',
  manufacturer: 'Vishay / Murata',
  revision: 'X7R Monolithic',
  datasheetUrl: 'https://www.vishay.com/docs/45233/kseries.pdf',
  dimensions: {
    widthMm: 5.0,
    heightMm: 7.5,
    depthMm: 3.2,
    massGrams: 0.2,
    mountingHolePitchMm: '5.08mm / 2.54mm Lead Spacing',
  },
  electrical: {
    operatingVoltage: 'Up to 50V DC',
    minVoltage: 0.0,
    maxVoltage: 50.0,
    logicLevel: 'High-Frequency Bypass',
    quiescentCurrentMa: 0,
    maxCurrentDrawMa: 50,
    powerRatingWatts: 0.1,
  },
  protocols: ['High-Frequency Bypass', 'IC VCC Decoupling', 'Noise Suppression'],
  mechanicalMounts: ['Through-Hole Radial Leads (2.54mm Breadboard Friendly)'],
  features: [
    '100 nF (0.1 µF, Code "104") Capacitance',
    'Class 2 X7R Temperature Stable Ceramic Dielectric (±15% from -55°C to +125°C)',
    '50V DC Maximum Working Voltage',
    'Ultra-low parasitic inductance for IC power rail decoupling',
    'Non-polarized: can be inserted in either orientation',
  ],
  subcomponents: [
    {
      id: 'sub_cer_disc',
      name: 'Epoxy Coated Ceramic Dielectric Disc',
      category: 'passive',
      partNumber: 'CER-X7R-104',
      manufacturer: 'Vishay',
      description: 'Multi-layer barium titanate ceramic dielectric with flame-retardant epoxy coating.',
      status: 'nominal',
      specifications: { capacitanceNf: 100, code: '104', dielectric: 'X7R' },
    },
  ],
};

// 14. REAL-TIME DIGITAL STORAGE OSCILLOSCOPE (DSO)
export const OscilloscopeSpecification: HardwareSpecification = {
  modelNumber: 'DS1054Z-DSO',
  manufacturer: 'Rigol Technologies',
  revision: 'UltraVision Hardware Rev 4',
  datasheetUrl: 'https://www.rigolna.com/products/digital-oscilloscopes/1000z/',
  dimensions: {
    widthMm: 313.1,
    heightMm: 160.8,
    depthMm: 122.4,
    massGrams: 3200.0,
    mountingHolePitchMm: 'Desktop Benchtop Stand & VESA 100mm',
  },
  electrical: {
    operatingVoltage: '100V - 240V AC Mains (Internal SMPS)',
    minVoltage: 100.0,
    maxVoltage: 240.0,
    logicLevel: 'Analog Voltage Probing (-50V to +50V CAT I)',
    quiescentCurrentMa: 250,
    maxCurrentDrawMa: 500,
    powerRatingWatts: 50.0,
  },
  protocols: ['Analog Probing', 'Digital PWM Decoding', 'UART/SPI/I2C Triggering', 'USB TMC', 'LXI LAN'],
  mechanicalMounts: ['Foldable Ergonomic Tilting Feet', 'Integrated Rugged Carry Handle', '4x BNC Front Panel Ports'],
  features: [
    '50 MHz Analog Bandwidth with 1 GSa/s Peak Real-Time Sample Rate',
    'Dual High-Impedance (1 MΩ // 15 pF) Analog Channels (CH1 Yellow / CH2 Cyan)',
    'Hardware PWM & Duty Cycle Frequency Counter with 6-Digit Precision',
    'Dedicated 1kHz 3V Square Wave Probe Compensation Calibration Lug',
    'Real-time FFT Spectral Analysis and Mathematical Waveform Processing',
    'Auto-Set Algorithm with 8x10 Dotted Phosphor Graticule Display',
  ],
  subcomponents: [
    {
      id: 'sub_dso_adc',
      name: 'High-Speed 1GSa/s Analog-to-Digital Converter',
      category: 'ic',
      partNumber: 'ADC08D1000',
      manufacturer: 'Texas Instruments',
      description: 'Dual 8-bit monolithic A/D converter digitizing input probe signals at up to 1 GSa/s.',
      status: 'nominal',
      specifications: { sampleRateMsps: 1000, resolutionBits: 8, channels: 2 },
    },
    {
      id: 'sub_dso_fpga',
      name: 'Waveform Processing FPGA & DSP Engine',
      category: 'ic',
      partNumber: 'XC6SLX16-CSG324',
      manufacturer: 'Xilinx',
      description: 'Spartan-6 FPGA executing real-time digital trigger correlation, decimation, and FFT display.',
      status: 'nominal',
      specifications: { logicCells: 14579, memoryKbits: 576 },
    },
    {
      id: 'sub_dso_bnc_ch1',
      name: 'CH1 Precision BNC Input Receptacle',
      category: 'connector',
      partNumber: 'BNC-PCB-50R',
      manufacturer: 'Amphenol',
      description: '50-ohm/1M-ohm switchable gold-plated center pin BNC jack with AC/DC relay coupling.',
      status: 'nominal',
      specifications: { impedanceOhm: 1000000, maxVoltageV: 300 },
    },
  ],
};
