import {
  DroneMotorSpec,
  DronePropellerSpec,
  DroneBatterySpec,
  DroneEscSpec,
  DroneFlightControllerSpec,
  DronePayloadSpec,
  DroneConfiguration,
} from './droneTypes';

// --- MOTORS CATALOG ---
export const DRONE_MOTORS_CATALOG: DroneMotorSpec[] = [
  {
    id: 'eco_ii_2207_2400kv',
    name: 'EMAX ECO II 2207 2400KV',
    partNumber: 'ECO-II-2207-2400KV',
    manufacturer: 'EMAX',
    kv: 2400,
    maxRpm: 35500,
    voltageMin: 11.1,
    voltageMax: 16.8, // 3-4S
    maxCurrentA: 42.5,
    maxPowerW: 710,
    maxThrustGrams: 1480,
    massGrams: 33.6,
    internalResistanceOhm: 0.046,
    torqueConstantNmPerA: 0.00398,
    statorSize: '2207',
    efficiency: 0.82,
  },
  {
    id: 'eco_ii_2207_1900kv',
    name: 'EMAX ECO II 2207 1900KV (High Voltage 6S)',
    partNumber: 'ECO-II-2207-1900KV',
    manufacturer: 'EMAX',
    kv: 1900,
    maxRpm: 42000,
    voltageMin: 14.8,
    voltageMax: 25.2, // 4-6S
    maxCurrentA: 38.0,
    maxPowerW: 860,
    maxThrustGrams: 1620,
    massGrams: 33.8,
    internalResistanceOhm: 0.062,
    torqueConstantNmPerA: 0.00502,
    statorSize: '2207',
    efficiency: 0.85,
  },
  {
    id: 't_motor_f60pro_2550kv',
    name: 'T-Motor F60 PRO IV 2550KV (High Output Racing)',
    partNumber: 'F60-PRO-IV-2550',
    manufacturer: 'T-Motor',
    kv: 2550,
    maxRpm: 38000,
    voltageMin: 11.1,
    voltageMax: 16.8,
    maxCurrentA: 49.5,
    maxPowerW: 820,
    maxThrustGrams: 1720,
    massGrams: 32.4,
    internalResistanceOhm: 0.038,
    torqueConstantNmPerA: 0.00374,
    statorSize: '2207.5',
    efficiency: 0.84,
  },
  {
    id: 'xing_e_pro_2208_1800kv',
    name: 'iFlight XING-E Pro 2208 1800KV (Long Range / Smooth)',
    partNumber: 'XING-E-2208-1800',
    manufacturer: 'iFlight',
    kv: 1800,
    maxRpm: 39500,
    voltageMin: 14.8,
    voltageMax: 25.2,
    maxCurrentA: 34.0,
    maxPowerW: 780,
    maxThrustGrams: 1540,
    massGrams: 36.5,
    internalResistanceOhm: 0.068,
    torqueConstantNmPerA: 0.00531,
    statorSize: '2208',
    efficiency: 0.87,
  },
];

// --- PROPELLERS CATALOG ---
export const DRONE_PROPELLERS_CATALOG: DronePropellerSpec[] = [
  {
    id: 'hq_5x43x3_v1s',
    name: 'HQProp DP 5x4.3x3 V1S (Balanced Freestyle)',
    partNumber: 'DP5X4.3X3V1S',
    manufacturer: 'HQProp',
    diameterInches: 5.0,
    pitchInches: 4.3,
    blades: 3,
    massGrams: 3.8,
    material: 'Polycarbonate',
    thrustCoefficientCt: 0.095,
    powerCoefficientCp: 0.042,
    maxRpm: 38000,
  },
  {
    id: 'hq_5x3x3',
    name: 'HQProp 5x3x3 (High Efficiency / Light Pitch)',
    partNumber: 'HQ5030-3',
    manufacturer: 'HQProp',
    diameterInches: 5.0,
    pitchInches: 3.0,
    blades: 3,
    massGrams: 3.2,
    material: 'Polycarbonate',
    thrustCoefficientCt: 0.076,
    powerCoefficientCp: 0.029,
    maxRpm: 42000,
  },
  {
    id: 'gemfan_51466_v2',
    name: 'Gemfan Hurricane 51466 V2 (Aggressive Grip)',
    partNumber: 'GEM-51466-V2',
    manufacturer: 'Gemfan',
    diameterInches: 5.1,
    pitchInches: 4.66,
    blades: 3,
    massGrams: 4.2,
    material: 'Polycarbonate Glass-Reinforced',
    thrustCoefficientCt: 0.112,
    powerCoefficientCp: 0.054,
    maxRpm: 36000,
  },
  {
    id: 'hq_6x4x3',
    name: 'HQProp 6x4x3 (6-inch Heavy Lift / High Thrust)',
    partNumber: 'HQ6040-3',
    manufacturer: 'HQProp',
    diameterInches: 6.0,
    pitchInches: 4.0,
    blades: 3,
    massGrams: 5.5,
    material: 'Glass Fiber Reinforced Nylon',
    thrustCoefficientCt: 0.138,
    powerCoefficientCp: 0.068,
    maxRpm: 30000,
  },
];

// --- BATTERIES CATALOG ---
export const DRONE_BATTERIES_CATALOG: DroneBatterySpec[] = [
  {
    id: 'cnhl_black_4s_1500mah',
    name: 'CNHL Black Series 4S 1500mAh 100C',
    partNumber: 'CNHL-1500-4S-100C',
    manufacturer: 'CNHL',
    cellCount: 4,
    cellNominalVoltage: 3.7,
    cellFullVoltage: 4.2,
    cellCutoffVoltage: 3.3,
    capacityMah: 1500,
    cRatingContinuous: 100,
    cRatingBurst: 200,
    massGrams: 195.0,
    internalResistanceOhmPerCell: 0.0035,
    connectorType: 'XT60 Female',
  },
  {
    id: 'tattu_rline_4s_1300mah',
    name: 'Tattu R-Line Version 4.0 4S 1300mAh 130C',
    partNumber: 'TA-RL-130C-1300-4S',
    manufacturer: 'Tattu / Gens Ace',
    cellCount: 4,
    cellNominalVoltage: 3.7,
    cellFullVoltage: 4.2,
    cellCutoffVoltage: 3.3,
    capacityMah: 1300,
    cRatingContinuous: 130,
    cRatingBurst: 260,
    massGrams: 152.0,
    internalResistanceOhmPerCell: 0.0024,
    connectorType: 'XT60 Female',
  },
  {
    id: 'tattu_rline_6s_1400mah',
    name: 'Tattu R-Line 6S 1400mAh 150C (High Voltage 22.2V)',
    partNumber: 'TA-RL-150C-1400-6S',
    manufacturer: 'Tattu / Gens Ace',
    cellCount: 6,
    cellNominalVoltage: 3.7,
    cellFullVoltage: 4.2,
    cellCutoffVoltage: 3.3,
    capacityMah: 1400,
    cRatingContinuous: 150,
    cRatingBurst: 300,
    massGrams: 238.0,
    internalResistanceOhmPerCell: 0.0022,
    connectorType: 'XT60 Female',
  },
  {
    id: 'cnhl_ministar_3s_2200mah',
    name: 'CNHL Ministar 3S 2200mAh 70C (Lower Voltage / Longer Hover)',
    partNumber: 'CNHL-2200-3S-70C',
    manufacturer: 'CNHL',
    cellCount: 3,
    cellNominalVoltage: 3.7,
    cellFullVoltage: 4.2,
    cellCutoffVoltage: 3.3,
    capacityMah: 2200,
    cRatingContinuous: 70,
    cRatingBurst: 140,
    massGrams: 178.0,
    internalResistanceOhmPerCell: 0.0042,
    connectorType: 'XT60 Female',
  },
];

// --- ESCS CATALOG ---
export const DRONE_ESCS_CATALOG: DroneEscSpec[] = [
  {
    id: 'speedybee_45a_4in1',
    name: 'SpeedyBee 45A BLHeli_S 4-in-1 ESC',
    partNumber: 'SPEEDYBEE-45A-4IN1',
    manufacturer: 'SpeedyBee',
    continuousCurrentA: 45,
    burstCurrentA: 55,
    protocol: 'DShot600',
    inputVoltageMin: 11.1,
    inputVoltageMax: 25.2,
    massGrams: 14.5,
  },
  {
    id: 'holybro_tekko32_65a',
    name: 'Holybro Tekko32 F4 Metal 65A 4-in-1 ESC',
    partNumber: 'TEKKO32-65A-METAL',
    manufacturer: 'Holybro',
    continuousCurrentA: 65,
    burstCurrentA: 75,
    protocol: 'DShot1200',
    inputVoltageMin: 11.1,
    inputVoltageMax: 29.4,
    massGrams: 18.2,
  },
];

// --- FLIGHT CONTROLLER CATALOG ---
export const DRONE_FC_CATALOG: DroneFlightControllerSpec[] = [
  {
    id: 'speedybee_f405_v3',
    name: 'SpeedyBee F405 V3 Flight Controller',
    partNumber: 'SPEEDYBEE-F405-V3',
    manufacturer: 'SpeedyBee',
    mcu: 'STM32F405 @ 168MHz',
    gyro: 'ICM-42688-P 6-DOF',
    massGrams: 9.2,
    pidFrequencyHz: 4000,
  },
  {
    id: 'matek_f722_se',
    name: 'Matek F722-SE Flight Controller',
    partNumber: 'MATEK-F722-SE',
    manufacturer: 'Matek Systems',
    mcu: 'STM32F722RET6 @ 216MHz',
    gyro: 'MPU6000 Low-Noise',
    massGrams: 10.5,
    pidFrequencyHz: 8000,
  },
];

// --- PAYLOADS CATALOG ---
export const DRONE_PAYLOADS_CATALOG: DronePayloadSpec[] = [
  {
    id: 'fpv_caddx_ratel2',
    name: 'Caddx Ratel 2 1200TVL FPV Micro Camera',
    type: 'camera',
    massGrams: 5.9,
    currentDrawMa: 180,
  },
  {
    id: 'gps_matek_m8q',
    name: 'Matek M8Q-5883 GPS & Compass + Mast',
    type: 'gps',
    massGrams: 14.0,
    currentDrawMa: 50,
  },
  {
    id: 'rx_elrs_nano',
    name: 'ExpressLRS 2.4GHz Nano Diversity Receiver',
    type: 'receiver',
    massGrams: 2.2,
    currentDrawMa: 60,
  },
  {
    id: 'vtx_tramp_800mw',
    name: 'TBS Unify Pro32 HV 5.8GHz VTX & Dipole',
    type: 'vtx',
    massGrams: 8.5,
    currentDrawMa: 450,
  },
  {
    id: 'action_gopro_bones',
    name: 'GoPro HERO10 Black Bones (HD Action Camera)',
    type: 'action_cam',
    massGrams: 54.0,
    currentDrawMa: 1200,
  },
];

// --- DEFAULT DOCUMENTED GEPRC MARK4 5" CONFIGURATION ---
export const DEFAULT_DRONE_CONFIG: DroneConfiguration = {
  id: 'geprc_mark4_freestyle_stock',
  name: 'GEPRC Mark4 5" Freestyle Reference (4S)',
  description: 'Standard 225mm True-X 5-inch carbon fiber freestyle quadcopter with 2207 2400KV motors, 5043 props, and 4S 1500mAh LiPo.',
  frame: {
    name: 'GEPRC Mark4 5" Carbon Fiber Airframe',
    model: 'MARK4-5IN-V2',
    wheelbaseMm: 225,
    frameMassGrams: 118.0,
    armLengthMeters: 0.1125, // 112.5mm arm reach from center
    geometry: 'true_x',
  },
  motors: [
    DRONE_MOTORS_CATALOG[0],
    DRONE_MOTORS_CATALOG[0],
    DRONE_MOTORS_CATALOG[0],
    DRONE_MOTORS_CATALOG[0],
  ],
  propellers: [
    DRONE_PROPELLERS_CATALOG[0],
    DRONE_PROPELLERS_CATALOG[0],
    DRONE_PROPELLERS_CATALOG[0],
    DRONE_PROPELLERS_CATALOG[0],
  ],
  battery: DRONE_BATTERIES_CATALOG[0], // 4S 1500mAh
  esc: DRONE_ESCS_CATALOG[0],
  flightController: DRONE_FC_CATALOG[0],
  payloads: [
    DRONE_PAYLOADS_CATALOG[0], // Camera
    DRONE_PAYLOADS_CATALOG[1], // GPS
    DRONE_PAYLOADS_CATALOG[2], // Receiver
    DRONE_PAYLOADS_CATALOG[3], // VTX
  ],
};
